name: Java CI

on:
  pull_request:
    types: [opened, reopened, review_requested]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build x times with Maven
        run: for i in {1..25}; do echo "Command no. $i"; mvn -Dmaven.test.skip.exec=true package; done
